### ISSUE TITLE
Editor doesn't show

### ISSUE THREAD

**Issue by hoop22** [insurance-technologies/ng-rooster#1]
I did exactly as the instruction tells, but the editor doesn't show up.

in app.module.ts 
```
import { BrowserModule } from '@angular/platform-browser';
import { NgModule } from '@angular/core';
import { FormsModule } from '@angular/forms';

import { AppRoutingModule } from './app-routing.module';
import { AppComponent } from './app.component';
import { NgRoosterModule } from '@instechnologies/ng-rooster';

@NgModule({
  declarations: [
    AppComponent
  ],
  imports: [
    BrowserModule,
    AppRoutingModule,
    NgRoosterModule, //import the NgRoosterModule
    FormsModule
  ],
  providers: [],
  bootstrap: [AppComponent]
})
export class AppModule { }

```
in app.component.html
```
<h1>Editor  </h1>
<rooster-editor-box></rooster-editor-box>

<router-outlet></router-outlet>
```

But the explorer just shows the h1 as Editor, no editor at all.

I've tried chrome and edge, with the same results.

**Comment by aleGuardiola** [comment]
Hi @hoop22  The editor component is a box itself without any size, I will update the readme to make it more clear.
The solution is to add css to the editor with width and height, that should solve the problem. Please let me know if that works for you

[Please take this as example](https://github.com/insurance-technologies/ng-rooster/blob/master/src/app/app.component.html)

**Comment by aleGuardiola** [comment]
Closing issue due to not response
