### ISSUE TITLE
Does this Editor has read only mode ?

### ISSUE THREAD

**Issue by raoshahid799** [insurance-technologies/ng-rooster#12]
how can we show the content of this editor . i search on internet i could not find read only mode of this editor.

**Comment by aleGuardiola** [comment]
@raoshahid799 the editor does not have a read only mode. The output of the content is an html format of it.

 <rooster-editor-box [(ngModel)]="content" ></rooster-editor-box>  -> content is the html content that you can render yourself using innerHtml for example

**Comment by raoshahid799** [comment]
yes its render the html but user can edit the content that is issue,

**Comment by aleGuardiola** [comment]
If you want to show the content you have to render it yourself using innerHtml
